table = int(input('Type a number to see the table: '))
print(11*'-')
print('{} x  1 = {}'.format(table, table*1))
print('{} x  2 = {}'.format(table, table*2))
print('{} x  3 = {}'.format(table, table*3))
print('{} x  4 = {}'.format(table, table*4))
print('{} x  5 = {}'.format(table, table*5))
print('{} x  6 = {}'.format(table, table*6))
print('{} x  7 = {}'.format(table, table*7))
print('{} x  8 = {}'.format(table, table*8))
print('{} x  9 = {}'.format(table, table*9))
print('{} x 10 = {}'.format(table, table*10))
print(11*'-')
