name = input('Type your full name: ')
print('Analyzing your name...')
print('Your name in uppercase {}'.format(name.upper()))
print('Your name in lowercase {}'.format(name.lower()))
print('Your name has {} letters '.format(len(name) - name.count(' ')))
fname = name.split()
print('Your first name has {} letters'.format(len(fname[0])))
